services:
    uam_user.change_password.success_listener:
        class: 'UAM\Bundle\UserBundle\EventListener\ChangePasswordSuccessListener'
        arguments: [@router, @session]
        tags:
            - { name: kernel.event_subscriber }

    # Override definition of fos_user.change_password.form.type service
    fos_user.change_password.form.type:
        class:  UAM\Bundle\UserBundle\Form\Type\ChangePasswordFormType
        arguments:  [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_change_password }
